// <auto-generated />
using System;
using DevFlow.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DevFlow.Persistence.Migrations
{
    [DbContext(typeof(DevFlowDbContext))]
    partial class DevFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DevFlow.Domain.Entities.Commit", b =>
                {
                    b.Property<string>("Sha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Sha");

                    b.HasIndex("TaskId");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DeveloperType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("GitHubToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitHubUser")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Developers");

                    b.HasDiscriminator<string>("DeveloperType").HasValue("Developer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("CommitSha")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("ReviewerId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CommitSha");

                    b.HasIndex("ReviewerId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Task", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("GitHubIssueId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("boolean");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.TimeLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("interval");

                    b.Property<int>("Phase")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TaskId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TimeLogs");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.UMLDiagram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LastSha")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("UMLDiagrams");
                });

            modelBuilder.Entity("TaskDependencies", b =>
                {
                    b.Property<int>("PrecursorId")
                        .HasColumnType("integer");

                    b.Property<int>("SuccessorId")
                        .HasColumnType("integer");

                    b.HasKey("PrecursorId", "SuccessorId");

                    b.HasIndex("SuccessorId");

                    b.ToTable("TaskDependencies");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.LeadDeveloper", b =>
                {
                    b.HasBaseType("DevFlow.Domain.Entities.Developer");

                    b.Property<int>("PrivilegeLevel")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("LeadDeveloper");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Commit", b =>
                {
                    b.HasOne("DevFlow.Domain.Entities.Task", "Task")
                        .WithMany("Commits")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("DevFlow.Domain.ValueObjects.SemanticVersion", "Version", b1 =>
                        {
                            b1.Property<string>("CommitSha")
                                .HasColumnType("character varying(40)");

                            b1.Property<int>("Major")
                                .HasColumnType("integer")
                                .HasColumnName("VersionMajor");

                            b1.Property<int>("Minor")
                                .HasColumnType("integer")
                                .HasColumnName("VersionMinor");

                            b1.Property<int>("Patch")
                                .HasColumnType("integer")
                                .HasColumnName("VersionPatch");

                            b1.HasKey("CommitSha");

                            b1.ToTable("Commits");

                            b1.WithOwner()
                                .HasForeignKey("CommitSha");
                        });

                    b.Navigation("Task");

                    b.Navigation("Version")
                        .IsRequired();
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Project", b =>
                {
                    b.HasOne("DevFlow.Domain.Entities.Developer", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Review", b =>
                {
                    b.HasOne("DevFlow.Domain.Entities.Commit", "Commit")
                        .WithMany("Reviews")
                        .HasForeignKey("CommitSha")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DevFlow.Domain.Entities.LeadDeveloper", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Commit");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Task", b =>
                {
                    b.HasOne("DevFlow.Domain.Entities.Project", "Project")
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.TimeLog", b =>
                {
                    b.HasOne("DevFlow.Domain.Entities.Task", "Task")
                        .WithMany("TimeLogs")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.UMLDiagram", b =>
                {
                    b.HasOne("DevFlow.Domain.Entities.Project", "Project")
                        .WithOne("UMLDiagram")
                        .HasForeignKey("DevFlow.Domain.Entities.UMLDiagram", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TaskDependencies", b =>
                {
                    b.HasOne("DevFlow.Domain.Entities.Task", null)
                        .WithMany()
                        .HasForeignKey("PrecursorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DevFlow.Domain.Entities.Task", null)
                        .WithMany()
                        .HasForeignKey("SuccessorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Commit", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Project", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("UMLDiagram");
                });

            modelBuilder.Entity("DevFlow.Domain.Entities.Task", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("TimeLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
